num = int(input('Digite um número: '))
tab1 = num * 1
tab2 = num * 2
tab3 = num * 3
tab4 = num * 4
tab5 = num * 5
tab6 = num * 6
tab7 = num * 7
tab8 = num * 8
tab9 = num * 9
tab10 = num * 10
print('A tabuada é:')
print('|{} X 1 = {}  |'.format(num, tab1))
print('|{} X 2 = {} |'.format(num, tab2))
print('|{} X 3 = {} |'.format(num, tab3))
print('|{} X 4 = {} |'.format(num, tab4))
print('|{} X 5 = {} |'.format(num, tab5))
print('|{} X 6 = {} |'.format(num, tab6))
print('|{} X 7 = {} |'.format(num, tab7))
print('|{} X 8 = {} |'.format(num, tab8))
print('|{} X 9 = {} |'.format(num, tab9))
print('|{} X 10 = {}|'.format(num, tab10))
