pessoa = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em letras maiúsculas: {}'.format(pessoa.upper()))
print('Seu nome em letras minúsculas: {}'.format(pessoa.lower()))
conta2 = pessoa.split()
juntar = ''.join(conta2)
print('Seu primeiro nome é {}.'.format(conta2[0]))
print('Seu nome tem {} letras'.format(len(juntar)))
#print('Seu nome tem {} letras'.format(len(pessoa) - pesso.count(' ')))
print('Seu primeiro nome tem {} letras'.format(len(conta2[0])))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
print('Seu último nome é {}.'.format(conta2[-1]))